### ISSUE TITLE
Number of columns seems to be incorrect

### ISSUE THREAD

**Issue by gbrunow** [yushi-hattori/DOIO-KB16-02-Wireless-VIA#1]
I was struggling to get my macropad setup, then I realized that whenever I reloaded Vial the keys would have shifted around.
I changed the number of columns from 8 to 7 and my issues went away.

**Comment by gbrunow** [comment]
Thanks for the file, btw.

**Comment by yushi-hattori** [comment]
Thanks, you're right!

Fixed in commit https://github.com/yushi-hattori/DOIO-KB16-02-Wireless-VIA/commit/1d63f9b094c7bc704982005cf9d4e7a34c0a359c
